"use client";

import React, { useState } from 'react';
import {
  Alert,
  Box,
  Button,
  Checkbox,
  FormControlLabel,
  IconButton,
  TextField,
  Tooltip,
  Typography,
} from '@mui/material';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import CheckIcon from '@mui/icons-material/Check';
import { WebhookTriggerConfig } from '@/shared/types/plannedExecution';

interface WebhookPanelProps {
  config: WebhookTriggerConfig;
  onChange: (config: WebhookTriggerConfig) => void;
  /** The execution id — pre-generated by the modal for unsaved executions. */
  executionId: string;
  /** Whether this execution has been saved yet (URL is live only after save). */
  saved: boolean;
}

/**
 * Webhook trigger editor: the call URL + token (available immediately — the
 * modal pre-generates the id/token for new executions), copy buttons, token
 * regeneration, and the external-callers opt-in.
 */
const WebhookPanel = ({ config, onChange, executionId, saved }: WebhookPanelProps) => {
  const [copied, setCopied] = useState<string | null>(null);

  const origin = typeof window !== 'undefined' ? window.location.origin : '';
  const url = `${origin}/api/webhooks/${executionId}`;

  const copy = async (label: string, value: string) => {
    try {
      await navigator.clipboard.writeText(value);
      setCopied(label);
      setTimeout(() => setCopied(null), 1500);
    } catch {
      /* clipboard unavailable */
    }
  };

  return (
    <Box sx={{ mt: 1 }}>
      {!saved && (
        <Alert severity="info" sx={{ mb: 2 }}>
          This URL and token are ready to copy now — they become active when
          you save.
        </Alert>
      )}

      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
        <TextField
          fullWidth
          label="Webhook URL"
          value={url}
          InputProps={{ readOnly: true }}
          size="small"
        />
        <Tooltip title="Copy URL">
          <IconButton onClick={() => copy('url', url)}>
            {copied === 'url' ? <CheckIcon color="success" /> : <ContentCopyIcon />}
          </IconButton>
        </Tooltip>
      </Box>
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mt: 2 }}>
        <TextField
          fullWidth
          label="Secret token"
          value={config.token}
          InputProps={{ readOnly: true }}
          size="small"
          type="password"
        />
        <Tooltip title="Copy token">
          <IconButton onClick={() => copy('token', config.token)} disabled={!config.token}>
            {copied === 'token' ? <CheckIcon color="success" /> : <ContentCopyIcon />}
          </IconButton>
        </Tooltip>
        <Button
          size="small"
          onClick={() => onChange({ ...config, token: crypto.randomUUID() })}
          sx={{ whiteSpace: 'nowrap' }}
        >
          New token
        </Button>
      </Box>
      <Typography variant="caption" color="text.secondary">
        {saved
          ? 'A new token takes effect when you save — callers using the old one are cut off.'
          : ''}
      </Typography>
      <Typography variant="body2" color="text.secondary" sx={{ mt: 1.5 }}>
        Callers send a POST with the token in the <code>X-Flujo-Token</code>{' '}
        header (or <code>?token=…</code>). The request body becomes part of
        the flow&apos;s input — treat it as untrusted data in your prompt.
      </Typography>

      <FormControlLabel
        sx={{ mt: 1, display: 'flex' }}
        control={
          <Checkbox
            checked={config.allowExternal === true}
            onChange={(e) => onChange({ ...config, allowExternal: e.target.checked })}
          />
        }
        label="Allow calls from other machines (default: this computer only)"
      />
      {config.allowExternal && (
        <Alert severity="warning">
          FLUJO assumes a single user on this machine. If you expose it beyond
          localhost (port forwarding, tunnels), securing that access is your
          responsibility — anyone with the URL and token can run this flow.
        </Alert>
      )}
    </Box>
  );
};

export default WebhookPanel;
