"use client";

import React, { useState } from 'react';
import {
  Alert,
  Box,
  Button,
  Checkbox,
  FormControlLabel,
  IconButton,
  TextField,
  Tooltip,
  Typography,
} from '@mui/material';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import CheckIcon from '@mui/icons-material/Check';
import { WebhookTriggerConfig } from '@/shared/types/plannedExecution';
import { useI18n } from '@/frontend/contexts/I18nContext';
import Trans from '@/frontend/components/shared/Trans';
import { withWorkspaceUrl } from '@/frontend/utils/workspaceSelection';

interface WebhookPanelProps {
  config: WebhookTriggerConfig;
  onChange: (config: WebhookTriggerConfig) => void;
  /** The execution id — pre-generated by the modal for unsaved executions. */
  executionId: string;
  /** Whether this execution has been saved yet (URL is live only after save). */
  saved: boolean;
}

/**
 * Webhook trigger editor: the call URL + token (available immediately — the
 * modal pre-generates the id/token for new executions), copy buttons, token
 * regeneration, and the external-callers opt-in.
 */
const WebhookPanel = ({ config, onChange, executionId, saved }: WebhookPanelProps) => {
  const { t } = useI18n();
  const [copied, setCopied] = useState<string | null>(null);

  const origin = typeof window !== 'undefined' ? window.location.origin : '';
  const url = withWorkspaceUrl(`${origin}/api/webhooks/${encodeURIComponent(executionId)}`);

  const copy = async (label: string, value: string) => {
    try {
      await navigator.clipboard.writeText(value);
      setCopied(label);
      setTimeout(() => setCopied(null), 1500);
    } catch {
      /* clipboard unavailable */
    }
  };

  return (
    <Box sx={{ mt: 1 }}>
      {!saved && (
        <Alert severity="info" sx={{ mb: 2 }}>
          {t('automations.webhook.pending')}
        </Alert>
      )}

      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
        <TextField
          fullWidth
          label={t('automations.webhook.url')}
          value={url}
          InputProps={{ readOnly: true }}
          size="small"
        />
        <Tooltip title={t('automations.webhook.copyUrl')}>
          <IconButton onClick={() => copy('url', url)}>
            {copied === 'url' ? <CheckIcon color="success" /> : <ContentCopyIcon />}
          </IconButton>
        </Tooltip>
      </Box>
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mt: 2 }}>
        <TextField
          fullWidth
          label={t('automations.webhook.secretToken')}
          value={config.token}
          InputProps={{ readOnly: true }}
          size="small"
          type="password"
        />
        <Tooltip title={t('automations.webhook.copyToken')}>
          <IconButton onClick={() => copy('token', config.token)} disabled={!config.token}>
            {copied === 'token' ? <CheckIcon color="success" /> : <ContentCopyIcon />}
          </IconButton>
        </Tooltip>
        <Button
          size="small"
          onClick={() => onChange({ ...config, token: crypto.randomUUID() })}
          sx={{ whiteSpace: 'nowrap' }}
        >
          {t('automations.webhook.newToken')}
        </Button>
      </Box>
      <Typography variant="caption" color="text.secondary">
        {saved
          ? t('automations.webhook.rotationHelp')
          : ''}
      </Typography>
      <Typography variant="body2" color="text.secondary" sx={{ mt: 1.5 }}>
        <Trans
          message="automations.webhook.instructions"
          values={{ header: <code>X-Flujo-Token</code>, query: <code>?token=…</code> }}
        />
      </Typography>

      <FormControlLabel
        sx={{ mt: 1, display: 'flex' }}
        control={
          <Checkbox
            checked={config.allowExternal === true}
            onChange={(e) => onChange({ ...config, allowExternal: e.target.checked })}
          />
        }
        label={t('automations.webhook.allowExternal')}
      />
      {config.allowExternal && (
        <Alert severity="warning">
          {t('automations.webhook.externalWarning')}
        </Alert>
      )}
    </Box>
  );
};

export default WebhookPanel;
