export type WorldLocale = 'es' | 'pt' | 'en';
const es = {
  hello: 'Un mundo por despertar.', guide: 'Estoy aquí. Vamos a empezar con la IA que ya usas.',
  ready: '¿Qué hacemos hoy?', readyBody: 'Dime lo que necesitas. Tu IA se encarga del trabajo.',
  discover: 'Encontrar mi IA', scanning: 'Buscando conexiones…', connect: 'Conecta tu IA',
  discoveryNote: 'Revisamos el equipo donde vive Flujo. Elegir una conexión inicia una prueba breve con tu proveedor.',
  saved: 'Guardada en Flujo', login: 'Inicio de sesión detectado', needsToken: 'Conectar con un token',
  needsLogin: 'Inicia sesión con Codex en este equipo', incompatible: 'Hay que reparar la conexión',
  unknown: 'No pudimos comprobar el inicio de sesión', runtimeMissing: 'El runtime de Flujo no está disponible',
  codexHelp: 'Usa codex login en el equipo de Flujo. Si usas keyring/auto, configura cli_auth_credentials_store = "file" y vuelve a iniciar sesión.',
  claudeHelp: 'Ejecuta claude setup-token. Pega el token aquí para que Flujo pueda usar tu suscripción.',
  token: 'Token de Claude', model: 'Modelo para pensar y trabajar', fallback: 'Opciones sugeridas; la prueba confirma acceso.',
  verify: 'Conectar y comprobar', verifying: 'Comprobando modelo y herramientas…', retry: 'Volver a buscar',
  other: 'Más opciones de IA', back: 'Volver', close: 'Cerrar', send: 'Enviar', draft: 'Habla conmigo o escribe aquí…',
  thinking: 'Pensando', listening: 'Escuchando', speaking: 'Hablando', usingApp: 'Trabajando', idle: 'A tu lado',
  waiting: 'Te necesito', error: 'Necesita atención', stop: 'Detener trabajo', stopSpeech: 'Silenciar voz',
  newChat: 'Nueva conversación', history: 'Ver conversación', inspect: 'Abrir en Flujo', world: 'Explorar mi mundo',
  brain: 'Mi IA', change: 'Cambiar', style: 'Compañero', quiet: 'Moss · tranquilo', measured: 'Orbit · sereno', bright: 'Spark · vivaz',
  guideIdentity: 'Guía de Flujo', talkTo: 'Conversar', identityNote: 'Este personaje usa su agente, modelos y memoria de Flujo.',
  springs: 'Manantiales', harbor: 'Puerto de apps', workshop: 'Taller de agentes', residents: 'Hogares',
  routines: 'Las esclusas', gathering: 'Punto de encuentro', market: 'Mercado', archive: 'Archivo', control: 'Casa de control',
  flows: 'Agentes', apps: 'Apps', personas: 'Personas', automations: 'Rutinas', meetings: 'Encuentros',
  empty: 'Este lugar empieza contigo.', viewAll: 'Ver todo', create: 'Abrir este lugar',
  unavailable: 'Algunas partes del mundo no están disponibles. Vuelve a intentarlo.',
  stale: 'Tu conexión cambió. Vamos a comprobarla otra vez.', noWork: 'Conecta una IA para empezar a trabajar.',
  apply: 'Aplicar', applied: 'Aplicado', steer: 'La indicación llegó al trabajo en curso.',
  uncertain: 'No pudimos confirmar la entrega. Revisa la conversación antes de reenviar.',
  steerNotReady: 'Aún no puedo recibir otra indicación. Tu texto se conserva.',
  connectFailed: 'La conexión no pasó la prueba. Puedes corregirla y volver a intentar.',
  voice: 'Hablar', voiceOutput: 'Escuchar al compañero', voiceOff: 'Voz desconectada', resources: 'Resultados', loading: 'Cargando tu mundo…',
};
type Copy = typeof es;
const pt: Copy = {
  hello: 'Um mundo para despertar.', guide: 'Estou aqui. Vamos começar com a IA que você já usa.',
  ready: 'O que vamos fazer hoje?', readyBody: 'Me conte o que precisa. Sua IA cuida do trabalho.',
  discover: 'Encontrar minha IA', scanning: 'Buscando conexões…', connect: 'Conecte sua IA',
  discoveryNote: 'Verificamos o computador onde o Flujo está. Escolher uma conexão inicia um teste breve com seu provedor.',
  saved: 'Salva no Flujo', login: 'Login detectado', needsToken: 'Conectar com um token', needsLogin: 'Entre no Codex neste computador',
  incompatible: 'A conexão precisa de reparo', unknown: 'Não foi possível verificar o login', runtimeMissing: 'O runtime do Flujo está indisponível',
  codexHelp: 'Use codex login no computador do Flujo. Para keyring/auto, configure cli_auth_credentials_store = "file" e entre novamente.',
  claudeHelp: 'Execute claude setup-token. Cole o token aqui para o Flujo usar sua assinatura.',
  token: 'Token do Claude', model: 'Modelo para pensar e trabalhar', fallback: 'Opções sugeridas; o teste confirma o acesso.',
  verify: 'Conectar e verificar', verifying: 'Verificando modelo e ferramentas…', retry: 'Buscar novamente', other: 'Mais opções de IA',
  back: 'Voltar', close: 'Fechar', send: 'Enviar', draft: 'Fale comigo ou escreva aqui…', thinking: 'Pensando', listening: 'Ouvindo',
  speaking: 'Falando', usingApp: 'Trabalhando', idle: 'Ao seu lado', waiting: 'Preciso de você', error: 'Precisa de atenção',
  stop: 'Parar trabalho', stopSpeech: 'Silenciar voz', newChat: 'Nova conversa', history: 'Ver conversa', inspect: 'Abrir no Flujo',
  world: 'Explorar meu mundo', brain: 'Minha IA', change: 'Trocar', style: 'Companheiro', quiet: 'Moss · tranquilo', measured: 'Orbit · sereno', bright: 'Spark · animado',
  guideIdentity: 'Guia do Flujo', talkTo: 'Conversar', identityNote: 'Este personagem usa seu agente, modelos e memória do Flujo.',
  springs: 'Nascentes', harbor: 'Porto de apps', workshop: 'Oficina de agentes', residents: 'Lares', routines: 'As eclusas', gathering: 'Ponto de encontro',
  market: 'Mercado', archive: 'Arquivo', control: 'Casa de controle', flows: 'Agentes', apps: 'Apps', personas: 'Personas', automations: 'Rotinas', meetings: 'Encontros',
  empty: 'Este lugar começa com você.', viewAll: 'Ver tudo', create: 'Abrir este lugar', unavailable: 'Algumas partes do mundo estão indisponíveis. Tente novamente.',
  stale: 'Sua conexão mudou. Vamos verificá-la novamente.', noWork: 'Conecte uma IA para começar a trabalhar.',
  apply: 'Aplicar', applied: 'Aplicado', steer: 'A orientação chegou ao trabalho em andamento.',
  uncertain: 'Não foi possível confirmar a entrega. Confira a conversa antes de reenviar.', connectFailed: 'A conexão não passou no teste. Você pode corrigi-la e tentar novamente.',
  steerNotReady: 'Ainda não posso receber outra orientação. Seu texto foi preservado.',
  voice: 'Conversar', voiceOutput: 'Ouvir o companheiro', voiceOff: 'Voz desconectada', resources: 'Resultados', loading: 'Carregando seu mundo…',
};
const en: Copy = {
  hello: 'A world waiting to wake.', guide: 'I’m here. Let’s start with the AI you already use.', ready: 'What shall we do today?', readyBody: 'Tell me what you need. Your AI handles the work.',
  discover: 'Find my AI', scanning: 'Finding connections…', connect: 'Connect your AI', discoveryNote: 'We inspect the machine hosting Flujo. Choosing a connection starts a brief test with your provider.',
  saved: 'Saved in Flujo', login: 'Login detected', needsToken: 'Connect with a token', needsLogin: 'Sign in to Codex on this machine', incompatible: 'Connection needs repair', unknown: 'We couldn’t verify the login',
  runtimeMissing: 'Flujo’s runtime is unavailable', codexHelp: 'Use codex login on the Flujo machine. For keyring/auto, set cli_auth_credentials_store = "file" and sign in again.',
  claudeHelp: 'Run claude setup-token. Paste the token here so Flujo can use your subscription.', token: 'Claude token', model: 'Model for thinking and working', fallback: 'Suggested options; the test confirms access.',
  verify: 'Connect and verify', verifying: 'Testing model and tools…', retry: 'Search again', other: 'More AI options', back: 'Back', close: 'Close', send: 'Send', draft: 'Talk to me or write here…',
  thinking: 'Thinking', listening: 'Listening', speaking: 'Speaking', usingApp: 'Working', idle: 'Here with you', waiting: 'I need you', error: 'Needs attention', stop: 'Stop work', stopSpeech: 'Silence voice',
  newChat: 'New conversation', history: 'View conversation', inspect: 'Open in Flujo', world: 'Explore my world', brain: 'My AI', change: 'Change', style: 'Companion', quiet: 'Moss · patient', measured: 'Orbit · measured', bright: 'Spark · lively',
  guideIdentity: 'Flujo guide', talkTo: 'Talk', identityNote: 'This character uses its existing Flujo agent, models and memory.',
  springs: 'Headwater Springs', harbor: 'Connector Harbor', workshop: 'Flowwright Workshop', residents: 'Homes', routines: 'The Lockworks', gathering: 'Gathering place', market: 'Riverside Market', archive: 'Archive', control: 'Control House',
  flows: 'Agents', apps: 'Apps', personas: 'Personas', automations: 'Routines', meetings: 'Meetings', empty: 'This place starts with you.', viewAll: 'View all', create: 'Open this place',
  unavailable: 'Some parts of the world are unavailable. Try again.', stale: 'Your connection changed. Let’s verify it again.', noWork: 'Connect an AI to start working.', apply: 'Apply', applied: 'Applied',
  steer: 'Your instruction reached the work in progress.', uncertain: 'Delivery could not be confirmed. Check the conversation before resending.', connectFailed: 'The connection did not pass the test. You can correct it and try again.',
  steerNotReady: 'Another instruction cannot be received yet. Your text is preserved.',
  voice: 'Talk', voiceOutput: 'Hear the companion', voiceOff: 'Voice disconnected', resources: 'Results', loading: 'Loading your world…',
};
export function worldCopy(locale: WorldLocale): Copy { return ({ es, pt, en })[locale]; }
