import { createHash } from 'crypto';
import { z } from 'zod';

import {
  BehaviorSlotKeySchema,
  CreatePersonaLeaseInputSchema,
  CreatePersonaMailboxItemInputSchema,
  ENDURING_AGENT_SCHEMA_VERSION,
  EnduringAgentIdSchema,
  PersonaActivitySchema,
  PersonaLeaseSchema,
  PersonaMailboxItemSchema,
  type BehaviorBinding,
  type BehaviorRevision,
  type CreatePersonaMailboxItemInput,
  type Persona,
  type PersonaActivity,
  type PersonaActivityStatus,
  type PersonaLease,
  type PersonaMailboxItem,
  type PersonaPriority,
} from '@/shared/types/enduringAgent';
import { assertSafeCollectionId, saveCollectionItem } from '@/utils/storage/backend';
import { getCurrentWorkspace } from '@/utils/workspace';

import { canonicalJson } from './behaviorRevisions';
import { ENDURING_AGENT_COLLECTIONS } from './collections';
import { randomEnduringAgentId, stableEnduringAgentId } from './ids';
import {
  type PersonaRuntimeLock,
  withPersonaRuntimeLock,
} from './runtimeLock';
import {
  getBehaviorRevision,
  getPersona,
  getPersonaActivity,
  getPersonaLease,
  getPersonaLeaseRecord,
  getPersonaMailboxItem,
  listBehaviorBindings,
  listPersonaBundle,
  listPersonaLeaseRecords,
  listPersonaMailboxItems,
  updatePersonaWithinRuntimeLock,
} from './store';

const LeaseFenceSchema = z.object({
  workspaceId: z.string().trim().min(1).max(256),
  personaId: EnduringAgentIdSchema,
  activityId: EnduringAgentIdSchema,
  leaseId: EnduringAgentIdSchema,
  holderId: EnduringAgentIdSchema,
  fencingToken: z.number().int().positive(),
}).strict();

const ClaimPersonaActivityInputSchema = z.object({
  personaId: EnduringAgentIdSchema,
  ttlMs: CreatePersonaLeaseInputSchema.shape.ttlMs,
}).strict();

const RenewPersonaActivityLeaseInputSchema = LeaseFenceSchema.extend({
  ttlMs: CreatePersonaLeaseInputSchema.shape.ttlMs,
}).strict();

const CompletePersonaActivityInputSchema = LeaseFenceSchema.extend({
  status: z.enum(['completed', 'cancelled', 'error']).optional(),
  outcomeRef: z.string().trim().max(4_096).optional(),
  error: z.string().trim().min(1).max(20_000).optional(),
}).strict().superRefine((input, ctx) => {
  if (input.status === 'error' && !input.error) {
    ctx.addIssue({
      code: 'custom',
      message: 'An errored Activity requires an error message.',
      path: ['error'],
    });
  }
  if (input.status !== 'error' && input.error !== undefined) {
    ctx.addIssue({
      code: 'custom',
      message: 'Only an errored Activity may include an error message.',
      path: ['error'],
    });
  }
});

export interface PersonaLeaseFence {
  workspaceId: string;
  personaId: string;
  activityId: string;
  leaseId: string;
  holderId: string;
  fencingToken: number;
}

export interface ClaimPersonaActivityInput {
  personaId: string;
  ttlMs: number;
}

interface ResolvedClaimPersonaActivityInput extends ClaimPersonaActivityInput {
  /** Opaque worker-incarnation capability generated by the runtime. */
  holderId: string;
}

export interface RenewPersonaActivityLeaseInput extends PersonaLeaseFence {
  ttlMs: number;
}

export interface CompletePersonaActivityInput extends PersonaLeaseFence {
  status?: Extract<PersonaActivityStatus, 'completed' | 'cancelled' | 'error'>;
  outcomeRef?: string;
  error?: string;
}

export interface EnqueuePersonaMailboxResult {
  item: PersonaMailboxItem;
  duplicate: boolean;
}

export interface PersonaActivityClaim {
  mailboxItem: PersonaMailboxItem;
  activity: PersonaActivity;
  lease: PersonaLease;
  recovered: boolean;
}

export interface CompletedPersonaActivity {
  mailboxItem: PersonaMailboxItem;
  activity: PersonaActivity;
  lease: PersonaLease;
}

export class PersonaRuntimeNotFoundError extends Error {
  readonly code = 'PERSONA_RUNTIME_NOT_FOUND' as const;

  constructor(readonly recordKind: string, readonly recordId: string) {
    super(`${recordKind} ${JSON.stringify(recordId)} not found in this workspace.`);
    this.name = 'PersonaRuntimeNotFoundError';
  }
}

export class PersonaRuntimeUnavailableError extends Error {
  readonly code = 'PERSONA_RUNTIME_UNAVAILABLE' as const;

  constructor(readonly personaId: string, message: string) {
    super(message);
    this.name = 'PersonaRuntimeUnavailableError';
  }
}

export class PersonaMailboxConflictError extends Error {
  readonly code = 'PERSONA_MAILBOX_CONFLICT' as const;

  constructor(readonly mailboxItemId: string, message: string) {
    super(message);
    this.name = 'PersonaMailboxConflictError';
  }
}

export class PersonaBusyError extends Error {
  readonly code = 'PERSONA_BUSY' as const;
  readonly activityId: string;
  readonly expiresAt: number;

  constructor(readonly personaId: string, lease: PersonaLease) {
    super(
      `Persona ${JSON.stringify(personaId)} is already leased by Activity `
      + `${JSON.stringify(lease.activityId)}.`,
    );
    this.name = 'PersonaBusyError';
    this.activityId = lease.activityId;
    this.expiresAt = lease.expiresAt;
  }
}

export class PersonaLeaseLostError extends Error {
  readonly code = 'PERSONA_LEASE_LOST' as const;

  constructor(readonly personaId: string, message: string) {
    super(message);
    this.name = 'PersonaLeaseLostError';
  }
}

export class PersonaRuntimeCorruptionError extends Error {
  readonly code = 'PERSONA_RUNTIME_CORRUPTION' as const;

  constructor(readonly personaId: string, message: string) {
    super(message);
    this.name = 'PersonaRuntimeCorruptionError';
  }
}

const PRIORITY_WEIGHT: Record<PersonaPriority, number> = {
  low: 0,
  normal: 1,
  high: 2,
  urgent: 3,
};
const LEASE_EXPIRY_ERROR = 'Activity lease expired before completion; automatic replay was suppressed.';

function sha256(value: string): string {
  return createHash('sha256').update(value).digest('hex');
}

function defaultBehaviorSlot(kind: PersonaMailboxItem['kind']): string {
  return kind === 'maintenance' ? 'maintain_memory' : 'primary';
}

function activityIdForMailbox(mailboxItemId: string): string {
  return stableEnduringAgentId('activity', {
    purpose: 'persona-mailbox-activity-v1',
    mailboxItemId,
  });
}

function leaseIdForAcquisition(
  workspaceId: string,
  personaId: string,
  activityId: string,
  fencingToken: number,
): string {
  return stableEnduringAgentId('lease', {
    purpose: 'persona-activity-lease-v1',
    workspaceId,
    personaId,
    activityId,
    fencingToken,
  });
}

function isTerminalActivity(activity: PersonaActivity): boolean {
  return activity.status === 'completed'
    || activity.status === 'cancelled'
    || activity.status === 'error';
}

function mailboxAdmission(record: PersonaMailboxItem): Record<string, unknown> {
  return {
    personaId: record.personaId,
    idempotencyKey: record.idempotencyKey,
    kind: record.kind,
    priority: record.priority,
    source: record.source,
    behaviorSlotKey: record.behaviorSlotKey ?? null,
    relationKey: record.relationKey ?? null,
    summary: record.summary ?? null,
    payloadRef: record.payloadRef ?? null,
    notBefore: record.notBefore ?? null,
  };
}

function leaseMatchesFence(lease: PersonaLease, fence: PersonaLeaseFence): boolean {
  return lease.workspaceId === fence.workspaceId
    && lease.workspaceId === getCurrentWorkspace()
    && lease.personaId === fence.personaId
    && lease.activityId === fence.activityId
    && lease.id === fence.leaseId
    && lease.holderId === fence.holderId
    && lease.fencingToken === fence.fencingToken;
}

async function saveActivity(
  lock: PersonaRuntimeLock,
  value: PersonaActivity,
): Promise<PersonaActivity> {
  const record = PersonaActivitySchema.parse(value) as PersonaActivity;
  await lock.assertOwned();
  await saveCollectionItem(ENDURING_AGENT_COLLECTIONS.activities, record.id, record);
  return record;
}

async function saveMailboxItem(
  lock: PersonaRuntimeLock,
  value: PersonaMailboxItem,
): Promise<PersonaMailboxItem> {
  const record = PersonaMailboxItemSchema.parse(value) as PersonaMailboxItem;
  await lock.assertOwned();
  await saveCollectionItem(ENDURING_AGENT_COLLECTIONS.mailboxItems, record.id, record);
  return record;
}

async function saveLeaseHead(
  lock: PersonaRuntimeLock,
  value: PersonaLease,
): Promise<PersonaLease> {
  const record = PersonaLeaseSchema.parse(value) as PersonaLease;
  // The acquisition record makes Activity.leaseId resolvable. The Persona-keyed
  // head remains the fencing authority and is written second/conservatively.
  await lock.assertOwned();
  await saveCollectionItem(ENDURING_AGENT_COLLECTIONS.leaseHistory, record.id, record);
  await lock.assertOwned();
  await saveCollectionItem(ENDURING_AGENT_COLLECTIONS.leases, record.personaId, record);
  return record;
}

async function saveLeaseHistoryRecord(
  lock: PersonaRuntimeLock,
  value: PersonaLease,
): Promise<PersonaLease> {
  const record = PersonaLeaseSchema.parse(value) as PersonaLease;
  await lock.assertOwned();
  await saveCollectionItem(ENDURING_AGENT_COLLECTIONS.leaseHistory, record.id, record);
  return record;
}

async function saveLeaseAuthorityHead(
  lock: PersonaRuntimeLock,
  value: PersonaLease,
): Promise<PersonaLease> {
  const record = PersonaLeaseSchema.parse(value) as PersonaLease;
  await lock.assertOwned();
  await saveCollectionItem(ENDURING_AGENT_COLLECTIONS.leases, record.personaId, record);
  return record;
}

function sameLeaseAcquisition(left: PersonaLease, right: PersonaLease): boolean {
  return left.id === right.id
    && left.workspaceId === right.workspaceId
    && left.personaId === right.personaId
    && left.activityId === right.activityId
    && left.holderId === right.holderId
    && left.fencingToken === right.fencingToken
    && left.acquiredAt === right.acquiredAt;
}

/** Repair every history-first/head-second crash prefix before using a fence. */
async function reconcilePersonaLeaseHead(
  lock: PersonaRuntimeLock,
  personaId: string,
): Promise<PersonaLease | null> {
  const [head, history] = await Promise.all([
    getPersonaLease(personaId),
    listPersonaLeaseRecords(personaId),
  ]);
  const byToken = new Map<number, PersonaLease>();
  for (const record of history) {
    const duplicate = byToken.get(record.fencingToken);
    if (duplicate && duplicate.id !== record.id) {
      throw new PersonaRuntimeCorruptionError(
        personaId,
        `Persona has multiple lease acquisitions for fencing token ${record.fencingToken}.`,
      );
    }
    byToken.set(record.fencingToken, record);
  }
  const latest = [...history].sort(
    (left, right) => right.fencingToken - left.fencingToken,
  )[0] ?? null;
  if (!latest) {
    if (head) {
      throw new PersonaRuntimeCorruptionError(
        personaId,
        `Persona lease head ${JSON.stringify(head.id)} has no acquisition history.`,
      );
    }
    return null;
  }

  for (const record of history) {
    if (record.fencingToken < latest.fencingToken && record.status === 'active') {
      await saveLeaseHistoryRecord(lock, {
        ...record,
        status: 'expired',
        releasedAt: undefined,
      });
    }
  }

  if (!head || head.fencingToken < latest.fencingToken) {
    return saveLeaseAuthorityHead(lock, latest);
  }
  if (head.fencingToken > latest.fencingToken || !sameLeaseAcquisition(head, latest)) {
    throw new PersonaRuntimeCorruptionError(
      personaId,
      'Persona lease head conflicts with its highest durable acquisition.',
    );
  }
  if (canonicalJson(head) === canonicalJson(latest)) return head;

  if (head.status === 'active') {
    if (
      latest.status !== 'active'
      || latest.renewedAt >= head.renewedAt
    ) {
      return saveLeaseAuthorityHead(lock, latest);
    }
  } else if (latest.status === 'active') {
    // The authority head is already terminal; repair lagging audit history.
    await saveLeaseHistoryRecord(lock, head);
    return head;
  } else if (head.status === latest.status) {
    return saveLeaseAuthorityHead(lock, latest);
  }
  throw new PersonaRuntimeCorruptionError(
    personaId,
    'Persona lease head and acquisition history have incompatible states.',
  );
}

async function projectPersonaLifecycle(
  lock: PersonaRuntimeLock,
  personaId: string,
  lifecycleState: Persona['lifecycleState'],
  now: number,
): Promise<Persona> {
  const persona = await getPersona(personaId);
  if (!persona) throw new PersonaRuntimeNotFoundError('Persona', personaId);
  if (
    persona.lifecycleState !== lifecycleState
    && (
      persona.lifecycleState === 'disabled'
      || persona.lifecycleState === 'sleeping'
      || persona.lifecycleState === 'error'
    )
  ) {
    // These are operator/corruption gates, not runtime projections. Expiry,
    // completion, or crash repair must never silently re-enable the actor.
    return persona;
  }
  if (persona.lifecycleState === lifecycleState && persona.updatedAt >= now) return persona;
  return updatePersonaWithinRuntimeLock({
    ...persona,
    lifecycleState,
    updatedAt: Math.max(now, persona.updatedAt),
  }, lock);
}

async function requireReadyPersona(personaId: string): Promise<Persona> {
  const persona = await getPersona(personaId);
  if (!persona) throw new PersonaRuntimeNotFoundError('Persona', personaId);
  if (persona.provisioningState !== 'ready') {
    throw new PersonaRuntimeUnavailableError(
      personaId,
      `Persona ${JSON.stringify(personaId)} has not completed provisioning.`,
    );
  }
  return persona;
}

async function resolveBehavior(
  personaId: string,
  slotKey: string,
): Promise<{ binding: BehaviorBinding; revision: BehaviorRevision }> {
  const matchingBindings = (await listBehaviorBindings(personaId)).filter(
    (candidate) => candidate.slotKey === slotKey,
  );
  if (matchingBindings.length > 1) {
    throw new PersonaRuntimeCorruptionError(
      personaId,
      `Persona has multiple Behaviors bound to slot ${JSON.stringify(slotKey)}.`,
    );
  }
  const binding = matchingBindings[0];
  if (!binding) {
    throw new PersonaRuntimeUnavailableError(
      personaId,
      `Persona ${JSON.stringify(personaId)} has no Behavior bound to slot `
      + `${JSON.stringify(slotKey)}.`,
    );
  }
  const revision = await getBehaviorRevision(binding.activeRevisionId);
  if (!revision) {
    throw new PersonaRuntimeCorruptionError(
      personaId,
      `BehaviorBinding ${JSON.stringify(binding.id)} references missing revision `
      + `${JSON.stringify(binding.activeRevisionId)}.`,
    );
  }
  if (
    revision.personaId !== personaId
    || revision.behaviorId !== binding.id
    || revision.slotKey !== binding.slotKey
  ) {
    throw new PersonaRuntimeCorruptionError(
      personaId,
      `BehaviorBinding ${JSON.stringify(binding.id)} does not own its active revision.`,
    );
  }
  return { binding, revision };
}

function sortEligibleMailboxItems(
  items: PersonaMailboxItem[],
  now: number,
): PersonaMailboxItem[] {
  return items
    .filter((item) => item.status === 'queued' && (item.notBefore ?? 0) <= now)
    .sort((left, right) => {
      const priority = PRIORITY_WEIGHT[right.priority] - PRIORITY_WEIGHT[left.priority];
      if (priority !== 0) return priority;
      const readyAt = (left.notBefore ?? left.createdAt) - (right.notBefore ?? right.createdAt);
      if (readyAt !== 0) return readyAt;
      const sequence = left.sequence - right.sequence;
      return sequence !== 0 ? sequence : left.id.localeCompare(right.id);
    });
}

function findMailboxForActivity(
  personaId: string,
  items: PersonaMailboxItem[],
  activityId: string,
): PersonaMailboxItem | null {
  const matches = items.filter(
    (item) => item.claimedActivityId === activityId
      || activityIdForMailbox(item.id) === activityId,
  );
  if (matches.length > 1) {
    throw new PersonaRuntimeCorruptionError(
      personaId,
      `Multiple mailbox items resolve to Activity ${JSON.stringify(activityId)}.`,
    );
  }
  return matches[0] ?? null;
}

async function terminalMailboxProjection(
  lock: PersonaRuntimeLock,
  item: PersonaMailboxItem,
  activity: PersonaActivity,
  now: number,
): Promise<PersonaMailboxItem> {
  const status = activity.status === 'completed' ? 'completed' : 'rejected';
  if (
    (item.status === 'coalesced' || item.status === 'completed' || item.status === 'rejected')
    && item.status !== status
  ) {
    throw new PersonaRuntimeCorruptionError(
      item.personaId,
      `Mailbox item ${JSON.stringify(item.id)} has terminal status `
      + `${JSON.stringify(item.status)} incompatible with Activity ${JSON.stringify(activity.id)}.`,
    );
  }
  if (
    item.status === status
    && item.claimedActivityId === activity.id
    && item.completedAt !== undefined
  ) {
    return item;
  }
  return saveMailboxItem(lock, {
    ...item,
    status,
    claimedActivityId: activity.id,
    coalescedIntoId: undefined,
    updatedAt: Math.max(now, item.updatedAt),
    completedAt: activity.completedAt ?? Math.max(now, item.createdAt),
  });
}

async function reconcileTerminalLease(
  lock: PersonaRuntimeLock,
  persona: Persona,
  lease: PersonaLease,
  activity: PersonaActivity,
  items: PersonaMailboxItem[],
): Promise<void> {
  const now = Math.max(Date.now(), activity.completedAt ?? activity.updatedAt, lease.renewedAt);
  const item = findMailboxForActivity(persona.id, items, activity.id);
  if (!item) {
    throw new PersonaRuntimeCorruptionError(
      persona.id,
      `Terminal Activity ${JSON.stringify(activity.id)} has no mailbox item.`,
    );
  }
  await terminalMailboxProjection(lock, item, activity, now);
  await projectPersonaLifecycle(lock, persona.id, 'idle', now);
  if (lease.status === 'active') {
    await saveLeaseHead(
      lock,
      activity.status === 'error' && activity.error === LEASE_EXPIRY_ERROR
        ? { ...lease, status: 'expired', releasedAt: undefined }
        : { ...lease, status: 'released', releasedAt: now },
    );
  }
}

/** Repair either crash boundary around a graceful waiting/yield transition. */
async function reconcileWaitingLease(
  lock: PersonaRuntimeLock,
  persona: Persona,
  lease: PersonaLease,
  activity: PersonaActivity,
  items: PersonaMailboxItem[],
): Promise<void> {
  if (activity.status !== 'waiting' || !activity.leaseId) {
    throw new PersonaRuntimeCorruptionError(
      persona.id,
      `Activity ${JSON.stringify(activity.id)} is not a lease-linked waiting Activity.`,
    );
  }
  const item = findMailboxForActivity(persona.id, items, activity.id);
  if (!item || item.status !== 'claimed' || item.claimedActivityId !== activity.id) {
    throw new PersonaRuntimeCorruptionError(
      persona.id,
      `Waiting Activity ${JSON.stringify(activity.id)} has no claimed mailbox item.`,
    );
  }
  const now = Math.max(Date.now(), activity.updatedAt, lease.renewedAt);

  if (activity.leaseId === lease.id) {
    // Yield persisted the Activity first and crashed before releasing the head.
    await projectPersonaLifecycle(lock, persona.id, 'waiting', now);
    await saveLeaseHead(lock, { ...lease, status: 'released', releasedAt: now });
    return;
  }

  // A resumed acquisition persisted its new head before repointing the waiting
  // Activity. The new capability was never returned; retire only that token and
  // preserve the prior released generation as the Activity's provenance.
  const prior = await getPersonaLeaseRecord(activity.leaseId);
  if (
    !prior
    || prior.workspaceId !== lease.workspaceId
    || prior.personaId !== persona.id
    || prior.activityId !== activity.id
    || prior.status !== 'released'
    || prior.fencingToken >= lease.fencingToken
  ) {
    throw new PersonaRuntimeCorruptionError(
      persona.id,
      `Waiting Activity ${JSON.stringify(activity.id)} references an invalid prior lease.`,
    );
  }
  await projectPersonaLifecycle(lock, persona.id, 'waiting', now);
  await saveLeaseHead(lock, { ...lease, status: 'expired', releasedAt: undefined });
}

async function expireActiveLease(
  lock: PersonaRuntimeLock,
  persona: Persona,
  lease: PersonaLease,
  items: PersonaMailboxItem[],
): Promise<void> {
  const now = Math.max(Date.now(), lease.renewedAt);
  const activity = await getPersonaActivity(lease.activityId);
  if (!activity || activity.personaId !== persona.id) {
    await projectPersonaLifecycle(lock, persona.id, 'error', now);
    await saveLeaseHead(lock, { ...lease, status: 'expired', releasedAt: undefined });
    throw new PersonaRuntimeCorruptionError(
      persona.id,
      `Expired lease ${JSON.stringify(lease.id)} references a missing or foreign Activity.`,
    );
  }
  if (isTerminalActivity(activity)) {
    await reconcileTerminalLease(lock, persona, lease, activity, items);
    return;
  }
  if (activity.status === 'waiting') {
    await reconcileWaitingLease(lock, persona, lease, activity, items);
    return;
  }

  const item = findMailboxForActivity(persona.id, items, activity.id);
  if (!item) {
    await projectPersonaLifecycle(lock, persona.id, 'error', now);
    await saveLeaseHead(lock, { ...lease, status: 'expired', releasedAt: undefined });
    throw new PersonaRuntimeCorruptionError(
      persona.id,
      `Expired Activity ${JSON.stringify(activity.id)} has no mailbox item.`,
    );
  }

  if (item.status === 'queued') {
    // The claim commit marker was never written, so the caller could not have
    // received a fence or dispatched side effects. Preserve the work and only
    // consume the abandoned acquisition token.
    await saveActivity(lock, {
      ...activity,
      status: 'queued',
      leaseId: undefined,
      startedAt: undefined,
      completedAt: undefined,
      error: undefined,
      updatedAt: Math.max(now, activity.updatedAt),
    });
    await projectPersonaLifecycle(lock, persona.id, 'idle', now);
    await saveLeaseHead(lock, { ...lease, status: 'expired', releasedAt: undefined });
    return;
  }

  // Unknown external side effects make automatic replay unsafe. Close the
  // interrupted Activity and leave explicit retry/recovery policy to a later
  // orchestration layer; independent queued work remains drainable.
  const failed = await saveActivity(lock, {
    ...activity,
    status: 'error',
    error: LEASE_EXPIRY_ERROR,
    updatedAt: Math.max(now, activity.updatedAt),
    completedAt: Math.max(now, activity.startedAt ?? activity.createdAt),
  });
  await terminalMailboxProjection(lock, item, failed, now);
  await projectPersonaLifecycle(lock, persona.id, 'idle', now);
  // Release/expiry is deliberately last: every earlier crash prefix leaves a
  // conservative active head that blocks takeover and can be reconciled.
  await saveLeaseHead(lock, { ...lease, status: 'expired', releasedAt: undefined });
}

async function ensureQueuedActivity(
  lock: PersonaRuntimeLock,
  item: PersonaMailboxItem,
  behaviorId: string,
  revision: BehaviorRevision,
): Promise<{ activity: PersonaActivity; created: boolean }> {
  const id = activityIdForMailbox(item.id);
  const existing = await getPersonaActivity(id);
  if (existing) {
    if (
      existing.personaId !== item.personaId
      || existing.kind !== item.kind
      || existing.behaviorId !== behaviorId
      || existing.behaviorRevisionId !== revision.id
    ) {
      throw new PersonaRuntimeCorruptionError(
        item.personaId,
        `Deterministic Activity ${JSON.stringify(id)} has conflicting content.`,
      );
    }
    return { activity: existing, created: false };
  }

  const activity = PersonaActivitySchema.parse({
    schemaVersion: ENDURING_AGENT_SCHEMA_VERSION,
    id,
    personaId: item.personaId,
    kind: item.kind,
    status: 'queued',
    source: {
      ...item.source,
      idempotencyKey: item.source.idempotencyKey ?? item.idempotencyKey,
    },
    behaviorId,
    behaviorRevisionId: revision.id,
    createdAt: item.createdAt,
    updatedAt: item.createdAt,
  }) as PersonaActivity;
  return { activity: await saveActivity(lock, activity), created: true };
}

async function acquireLeaseForActivity(
  lock: PersonaRuntimeLock,
  input: ResolvedClaimPersonaActivityInput,
  activity: PersonaActivity,
  previousHead: PersonaLease | null,
): Promise<PersonaLease> {
  const leaseHistory = await listPersonaLeaseRecords(input.personaId);
  const durableToken = leaseHistory.reduce(
    (maximum, candidate) => Math.max(maximum, candidate.fencingToken),
    previousHead?.fencingToken ?? 0,
  );
  const durableTimestamp = leaseHistory.reduce(
    (maximum, candidate) => Math.max(maximum, candidate.renewedAt),
    previousHead?.renewedAt ?? 0,
  );
  let fencingToken = durableToken + 1;

  while (true) {
    const workspaceId = getCurrentWorkspace();
    const id = leaseIdForAcquisition(workspaceId, input.personaId, activity.id, fencingToken);
    const orphan = await getPersonaLeaseRecord(id);
    if (orphan) {
      if (
        orphan.personaId !== input.personaId
        || orphan.workspaceId !== workspaceId
        || orphan.activityId !== activity.id
        || orphan.holderId !== input.holderId
        || orphan.fencingToken !== fencingToken
      ) {
        throw new PersonaRuntimeCorruptionError(
          input.personaId,
          `Lease acquisition ${JSON.stringify(id)} has conflicting durable history.`,
        );
      }
      if (orphan.status === 'active' && orphan.expiresAt > Date.now()) {
        return saveLeaseHead(lock, orphan);
      }
      // An orphaned/terminal acquisition still consumed its token. Advance the
      // durable head before allocating the next one so tokens are never reused.
      const consumed = orphan.status === 'active'
        ? { ...orphan, status: 'expired' as const }
        : orphan;
      await saveLeaseHead(lock, consumed);
      fencingToken = consumed.fencingToken + 1;
      continue;
    }

    const acquiredAt = Math.max(
      Date.now(),
      activity.createdAt,
      activity.updatedAt,
      durableTimestamp,
    );
    const lease = PersonaLeaseSchema.parse({
      schemaVersion: ENDURING_AGENT_SCHEMA_VERSION,
      id,
      workspaceId,
      personaId: input.personaId,
      activityId: activity.id,
      holderId: input.holderId,
      status: 'active',
      fencingToken,
      acquiredAt,
      renewedAt: acquiredAt,
      expiresAt: acquiredAt + input.ttlMs,
    }) as PersonaLease;
    return saveLeaseHead(lock, lease);
  }
}

async function repairActiveClaim(
  lock: PersonaRuntimeLock,
  persona: Persona,
  lease: PersonaLease,
  item: PersonaMailboxItem,
  activity: PersonaActivity,
): Promise<PersonaActivityClaim> {
  const now = Math.max(Date.now(), activity.updatedAt, item.updatedAt, lease.acquiredAt);
  let repairedActivity = activity;
  if (activity.status === 'queued' || activity.status === 'waiting') {
    repairedActivity = await saveActivity(lock, {
      ...activity,
      status: 'running',
      leaseId: lease.id,
      startedAt: activity.startedAt ?? lease.acquiredAt,
      updatedAt: now,
      completedAt: undefined,
      error: undefined,
    });
  } else if (activity.status !== 'running') {
    throw new PersonaRuntimeCorruptionError(
      persona.id,
      `Active lease ${JSON.stringify(lease.id)} points at terminal Activity `
      + `${JSON.stringify(activity.id)}.`,
    );
  } else if (activity.leaseId !== lease.id) {
    throw new PersonaRuntimeCorruptionError(
      persona.id,
      `Running Activity ${JSON.stringify(activity.id)} is linked to lease `
      + `${JSON.stringify(activity.leaseId)} instead of ${JSON.stringify(lease.id)}.`,
    );
  }

  let repairedItem = item;
  if (item.status === 'queued') {
    repairedItem = await saveMailboxItem(lock, {
      ...item,
      status: 'claimed',
      claimedActivityId: activity.id,
      updatedAt: now,
    });
  } else if (item.status !== 'claimed' || item.claimedActivityId !== activity.id) {
    throw new PersonaRuntimeCorruptionError(
      persona.id,
      `Active Activity ${JSON.stringify(activity.id)} has incompatible mailbox state.`,
    );
  }

  await projectPersonaLifecycle(lock, persona.id, 'busy', now);
  return {
    mailboxItem: repairedItem,
    activity: repairedActivity,
    lease,
    recovered: true,
  };
}

async function claimQueuedItem(
  lock: PersonaRuntimeLock,
  persona: Persona,
  input: ResolvedClaimPersonaActivityInput,
  item: PersonaMailboxItem,
  previousHead: PersonaLease | null,
): Promise<PersonaActivityClaim | null> {
  if (
    (item.status !== 'queued' && item.status !== 'claimed')
    || (item.status === 'claimed' && item.claimedActivityId !== activityIdForMailbox(item.id))
  ) {
    throw new PersonaRuntimeCorruptionError(
      persona.id,
      `Mailbox item ${JSON.stringify(item.id)} cannot be claimed from status `
      + `${JSON.stringify(item.status)}.`,
    );
  }
  const slotKey = item.behaviorSlotKey ?? defaultBehaviorSlot(item.kind);
  const activityId = activityIdForMailbox(item.id);
  const pinnedActivity = await getPersonaActivity(activityId);
  let behaviorId: string;
  let revision: BehaviorRevision;
  if (pinnedActivity) {
    if (!pinnedActivity.behaviorId || !pinnedActivity.behaviorRevisionId) {
      throw new PersonaRuntimeCorruptionError(
        persona.id,
        `Persisted Activity ${JSON.stringify(activityId)} has no immutable Behavior pin.`,
      );
    }
    const pinnedRevision = await getBehaviorRevision(pinnedActivity.behaviorRevisionId);
    if (
      !pinnedRevision
      || pinnedRevision.personaId !== persona.id
      || pinnedRevision.behaviorId !== pinnedActivity.behaviorId
      || pinnedRevision.slotKey !== slotKey
    ) {
      throw new PersonaRuntimeCorruptionError(
        persona.id,
        `Persisted Activity ${JSON.stringify(activityId)} has an invalid Behavior pin.`,
      );
    }
    behaviorId = pinnedActivity.behaviorId;
    revision = pinnedRevision;
  } else {
    const resolved = await resolveBehavior(persona.id, slotKey);
    behaviorId = resolved.binding.id;
    revision = resolved.revision;
  }
  const ensured = await ensureQueuedActivity(lock, item, behaviorId, revision);
  if (isTerminalActivity(ensured.activity)) {
    await terminalMailboxProjection(lock, item, ensured.activity, Date.now());
    return null;
  }

  const lease = await acquireLeaseForActivity(lock, input, ensured.activity, previousHead);
  const claim = await repairActiveClaim(lock, persona, lease, item, ensured.activity);
  return { ...claim, recovered: !ensured.created };
}

/**
 * Admit one durable input. Identity is derived solely from Persona plus a hash
 * of the caller retry key, so duplicate enforcement is a fail-closed point read
 * rather than a best-effort collection scan.
 */
export async function enqueuePersonaMailboxItem(
  value: unknown,
): Promise<EnqueuePersonaMailboxResult> {
  const input = CreatePersonaMailboxItemInputSchema.parse(value) as CreatePersonaMailboxItemInput;
  assertSafeCollectionId(input.personaId);

  return withPersonaRuntimeLock(input.personaId, async (lock) => {
    const idempotencyKey = sha256(input.idempotencyKey);
    const source = {
      ...input.source,
      ...(input.source.idempotencyKey
        ? { idempotencyKey: sha256(input.source.idempotencyKey) }
        : {}),
    };
    const behaviorSlotKey = input.behaviorSlotKey ?? defaultBehaviorSlot(input.kind);
    BehaviorSlotKeySchema.parse(behaviorSlotKey);

    const id = stableEnduringAgentId('mailbox', {
      purpose: 'persona-mailbox-idempotency-v1',
      personaId: input.personaId,
      idempotencyKey,
    });
    const requestedAdmission = {
      personaId: input.personaId,
      idempotencyKey,
      kind: input.kind,
      priority: input.priority ?? 'normal',
      source,
      behaviorSlotKey,
      relationKey: input.relationKey ?? null,
      summary: input.summary ?? null,
      payloadRef: input.payloadRef ?? null,
      notBefore: input.notBefore ?? null,
    };

    const existing = await getPersonaMailboxItem(id);
    if (existing) {
      if (canonicalJson(mailboxAdmission(existing)) !== canonicalJson(requestedAdmission)) {
        throw new PersonaMailboxConflictError(
          id,
          `Mailbox idempotency key for Persona ${JSON.stringify(input.personaId)} was reused `
          + 'with different work.',
        );
      }
      return { item: existing, duplicate: true };
    }

    const persona = await requireReadyPersona(input.personaId);
    if (persona.lifecycleState === 'disabled') {
      throw new PersonaRuntimeUnavailableError(
        persona.id,
        `Persona ${JSON.stringify(persona.id)} is disabled and cannot accept new work.`,
      );
    }
    await resolveBehavior(persona.id, behaviorSlotKey);

    const existingItems = await listPersonaMailboxItems(persona.id);
    const sequences = new Set(existingItems.map((item) => item.sequence));
    if (sequences.size !== existingItems.length) {
      throw new PersonaRuntimeCorruptionError(
        persona.id,
        'Persona mailbox contains duplicate admission sequence values.',
      );
    }
    const sequence = existingItems.reduce(
      (maximum, item) => Math.max(maximum, item.sequence),
      0,
    ) + 1;
    const now = Date.now();
    const candidate = PersonaMailboxItemSchema.parse({
      schemaVersion: ENDURING_AGENT_SCHEMA_VERSION,
      id,
      personaId: persona.id,
      idempotencyKey,
      sequence,
      kind: input.kind,
      priority: input.priority ?? 'normal',
      status: 'queued',
      source,
      behaviorSlotKey,
      ...(input.relationKey !== undefined ? { relationKey: input.relationKey } : {}),
      ...(input.summary !== undefined ? { summary: input.summary } : {}),
      ...(input.payloadRef !== undefined ? { payloadRef: input.payloadRef } : {}),
      ...(input.notBefore !== undefined ? { notBefore: input.notBefore } : {}),
      createdAt: now,
      updatedAt: now,
    }) as PersonaMailboxItem;

    return { item: await saveMailboxItem(lock, candidate), duplicate: false };
  });
}

/**
 * Claim the next eligible item. Existing valid work blocks other holders;
 * expiry closes uncertain work instead of replaying possible side effects.
 */
export async function claimNextPersonaActivity(
  value: unknown,
): Promise<PersonaActivityClaim | null> {
  const input = ClaimPersonaActivityInputSchema.parse(value) as ClaimPersonaActivityInput;
  assertSafeCollectionId(input.personaId);

  return withPersonaRuntimeLock(input.personaId, async (lock) => {
    const acquisitionInput: ResolvedClaimPersonaActivityInput = {
      ...input,
      holderId: randomEnduringAgentId('holder'),
    };
    for (let attempt = 0; attempt < 100; attempt += 1) {
      const persona = await requireReadyPersona(input.personaId);
      const items = await listPersonaMailboxItems(persona.id);
      const head = await reconcilePersonaLeaseHead(lock, persona.id);
      if (head?.status === 'active') {
        const activity = await getPersonaActivity(head.activityId);
        if (!activity || activity.personaId !== persona.id) {
          await expireActiveLease(lock, persona, head, items);
          continue;
        }
        if (isTerminalActivity(activity)) {
          await reconcileTerminalLease(lock, persona, head, activity, items);
          continue;
        }
        if (activity.status === 'waiting') {
          await reconcileWaitingLease(lock, persona, head, activity, items);
          continue;
        }
        const item = findMailboxForActivity(persona.id, items, activity.id);
        if (item?.status === 'queued') {
          // The durable claim marker was never reached, so no caller could have
          // received this fence. Retire the abandoned acquisition immediately
          // instead of making provably-undispatched work wait for lease expiry.
          await expireActiveLease(lock, persona, head, items);
          continue;
        }
        if (head.expiresAt <= Date.now()) {
          await expireActiveLease(lock, persona, head, items);
          continue;
        }
        if (!item || item.status !== 'claimed' || item.claimedActivityId !== activity.id) {
          throw new PersonaRuntimeCorruptionError(
            persona.id,
            `Live Activity ${JSON.stringify(activity.id)} has incompatible mailbox state.`,
          );
        }
        await repairActiveClaim(lock, persona, head, item, activity);
        throw new PersonaBusyError(persona.id, head);
      }

      if (
        persona.lifecycleState === 'disabled'
        || persona.lifecycleState === 'sleeping'
        || persona.lifecycleState === 'error'
      ) {
        throw new PersonaRuntimeUnavailableError(
          persona.id,
          `Persona ${JSON.stringify(persona.id)} is ${persona.lifecycleState}.`,
        );
      }

      const claimed = items.filter((item) => item.status === 'claimed');
      if (claimed.length === 1) {
        const item = claimed[0];
        const activity = await getPersonaActivity(activityIdForMailbox(item.id));
        if (activity?.status === 'waiting') {
          const prior = activity.leaseId
            ? await getPersonaLeaseRecord(activity.leaseId)
            : null;
          if (
            !head
            || !prior
            || prior.workspaceId !== getCurrentWorkspace()
            || prior.personaId !== persona.id
            || prior.activityId !== activity.id
            || prior.status !== 'released'
            || prior.fencingToken > head.fencingToken
          ) {
            throw new PersonaRuntimeCorruptionError(
              persona.id,
              `Waiting Activity ${JSON.stringify(activity.id)} has no durable released lease `
              + 'provenance.',
            );
          }
          return claimQueuedItem(lock, persona, acquisitionInput, item, head);
        }
      }
      if (claimed.length > 0) {
        throw new PersonaRuntimeCorruptionError(
          persona.id,
          `Persona has ${claimed.length} claimed mailbox item(s) without a recoverable lease head.`,
        );
      }

      const next = sortEligibleMailboxItems(items, Date.now())[0];
      if (!next) {
        if (persona.lifecycleState === 'busy' || persona.lifecycleState === 'waiting') {
          await projectPersonaLifecycle(lock, persona.id, 'idle', Date.now());
        }
        return null;
      }
      const claimedNext = await claimQueuedItem(lock, persona, acquisitionInput, next, head);
      if (claimedNext) return claimedNext;
    }
    throw new PersonaRuntimeCorruptionError(
      input.personaId,
      'Persona runtime reconciliation exceeded its bounded attempt limit.',
    );
  });
}

async function requireCurrentLease(
  lock: PersonaRuntimeLock,
  personaId: string,
  fence: PersonaLeaseFence,
): Promise<PersonaLease> {
  const lease = await reconcilePersonaLeaseHead(lock, personaId);
  if (!lease || !leaseMatchesFence(lease, fence)) {
    throw new PersonaLeaseLostError(
      personaId,
      `Persona lease ${JSON.stringify(fence.leaseId)} is no longer current.`,
    );
  }
  return lease;
}

async function requireRunnableActivityForLease(
  lock: PersonaRuntimeLock,
  persona: Persona,
  lease: PersonaLease,
): Promise<PersonaActivity> {
  const activity = await getPersonaActivity(lease.activityId);
  if (!activity || activity.personaId !== persona.id) {
    throw new PersonaRuntimeCorruptionError(
      persona.id,
      `Persona lease ${JSON.stringify(lease.id)} references a missing or foreign Activity.`,
    );
  }
  if (isTerminalActivity(activity)) {
    await reconcileTerminalLease(
      lock,
      persona,
      lease,
      activity,
      await listPersonaMailboxItems(persona.id),
    );
    throw new PersonaLeaseLostError(
      persona.id,
      `Persona Activity ${JSON.stringify(activity.id)} is already terminal.`,
    );
  }
  if (activity.status === 'waiting') {
    await reconcileWaitingLease(
      lock,
      persona,
      lease,
      activity,
      await listPersonaMailboxItems(persona.id),
    );
    throw new PersonaLeaseLostError(
      persona.id,
      `Persona Activity ${JSON.stringify(activity.id)} has yielded its lease.`,
    );
  }
  if (activity.status !== 'running' || activity.leaseId !== lease.id) {
    throw new PersonaLeaseLostError(
      persona.id,
      `Persona Activity ${JSON.stringify(activity.id)} is not running under lease `
      + `${JSON.stringify(lease.id)}.`,
    );
  }
  return activity;
}

/** Verify the exact live fencing tuple immediately before external dispatch. */
export async function assertPersonaActivityLease(value: unknown): Promise<PersonaLease> {
  const fence = LeaseFenceSchema.parse(value) as PersonaLeaseFence;
  return withPersonaRuntimeLock(fence.personaId, async (lock) => {
    const persona = await requireReadyPersona(fence.personaId);
    const lease = await requireCurrentLease(lock, persona.id, fence);
    if (lease.status !== 'active' || lease.expiresAt <= Date.now()) {
      if (lease.status === 'active') {
        await expireActiveLease(lock, persona, lease, await listPersonaMailboxItems(persona.id));
      }
      throw new PersonaLeaseLostError(
        persona.id,
        `Persona lease ${JSON.stringify(lease.id)} is not active.`,
      );
    }
    await requireRunnableActivityForLease(lock, persona, lease);
    return lease;
  });
}

export async function renewPersonaActivityLease(value: unknown): Promise<PersonaLease> {
  const input = RenewPersonaActivityLeaseInputSchema.parse(value) as RenewPersonaActivityLeaseInput;
  return withPersonaRuntimeLock(input.personaId, async (lock) => {
    const persona = await requireReadyPersona(input.personaId);
    const lease = await requireCurrentLease(lock, persona.id, input);
    if (lease.status !== 'active' || lease.expiresAt <= Date.now()) {
      if (lease.status === 'active') {
        await expireActiveLease(lock, persona, lease, await listPersonaMailboxItems(persona.id));
      }
      throw new PersonaLeaseLostError(
        persona.id,
        `Persona lease ${JSON.stringify(lease.id)} expired before renewal.`,
      );
    }
    await requireRunnableActivityForLease(lock, persona, lease);

    const renewedAt = Math.max(Date.now(), lease.renewedAt);
    return saveLeaseHead(lock, {
      ...lease,
      renewedAt,
      expiresAt: renewedAt + input.ttlMs,
    });
  });
}

/**
 * Gracefully yield active work. The Activity becomes waiting and can later be
 * reacquired with a strictly higher token; raw lease mutation stays internal.
 */
export async function releasePersonaActivityLease(value: unknown): Promise<PersonaLease> {
  const fence = LeaseFenceSchema.parse(value) as PersonaLeaseFence;
  return withPersonaRuntimeLock(fence.personaId, async (lock) => {
    const persona = await requireReadyPersona(fence.personaId);
    const lease = await requireCurrentLease(lock, persona.id, fence);
    if (lease.status === 'released') return lease;
    if (lease.status !== 'active' || lease.expiresAt <= Date.now()) {
      if (lease.status === 'active') {
        await expireActiveLease(lock, persona, lease, await listPersonaMailboxItems(persona.id));
      }
      throw new PersonaLeaseLostError(
        persona.id,
        `Persona lease ${JSON.stringify(lease.id)} cannot be released after expiry.`,
      );
    }

    const activity = await getPersonaActivity(lease.activityId);
    if (!activity || activity.personaId !== persona.id) {
      throw new PersonaRuntimeCorruptionError(
        persona.id,
        `Persona lease ${JSON.stringify(lease.id)} references a missing or foreign Activity.`,
      );
    }
    const now = Math.max(Date.now(), lease.renewedAt, activity.updatedAt);
    if (isTerminalActivity(activity)) {
      await reconcileTerminalLease(
        lock,
        persona,
        lease,
        activity,
        await listPersonaMailboxItems(persona.id),
      );
      return (await getPersonaLease(persona.id))!;
    }
    if (activity.status === 'waiting') {
      await reconcileWaitingLease(
        lock,
        persona,
        lease,
        activity,
        await listPersonaMailboxItems(persona.id),
      );
      return (await getPersonaLease(persona.id))!;
    }
    if (activity.status !== 'running' || activity.leaseId !== lease.id) {
      throw new PersonaLeaseLostError(
        persona.id,
        `Persona Activity ${JSON.stringify(activity.id)} is not running under lease `
        + `${JSON.stringify(lease.id)}.`,
      );
    }

    await saveActivity(lock, {
      ...activity,
      status: 'waiting',
      startedAt: activity.startedAt ?? lease.acquiredAt,
      updatedAt: now,
    });
    await projectPersonaLifecycle(lock, persona.id, 'waiting', now);
    return saveLeaseHead(lock, {
      ...lease,
      status: 'released',
      releasedAt: now,
    });
  });
}

function completionMatches(
  activity: PersonaActivity,
  input: CompletePersonaActivityInput,
): boolean {
  return activity.status === (input.status ?? 'completed')
    && (activity.outcomeRef ?? undefined) === input.outcomeRef
    && (activity.error ?? undefined) === input.error;
}

/** Complete an Activity and release its authoritative lease last. */
export async function completePersonaActivity(
  value: unknown,
): Promise<CompletedPersonaActivity> {
  const input = CompletePersonaActivityInputSchema.parse(value) as CompletePersonaActivityInput;
  return withPersonaRuntimeLock(input.personaId, async (lock) => {
    const persona = await requireReadyPersona(input.personaId);
    const lease = await requireCurrentLease(lock, persona.id, input);
    const activity = await getPersonaActivity(input.activityId);
    if (!activity || activity.personaId !== persona.id) {
      throw new PersonaRuntimeNotFoundError('PersonaActivity', input.activityId);
    }
    const items = await listPersonaMailboxItems(persona.id);
    const item = findMailboxForActivity(persona.id, items, activity.id);
    if (!item) {
      throw new PersonaRuntimeCorruptionError(
        persona.id,
        `Activity ${JSON.stringify(activity.id)} has no mailbox item.`,
      );
    }

    if (isTerminalActivity(activity)) {
      if (!completionMatches(activity, input)) {
        throw new PersonaLeaseLostError(
          persona.id,
          `Activity ${JSON.stringify(activity.id)} already has a different terminal outcome.`,
        );
      }
      await reconcileTerminalLease(lock, persona, lease, activity, items);
      return {
        activity,
        mailboxItem: (await getPersonaMailboxItem(item.id))!,
        lease: (await getPersonaLease(persona.id))!,
      };
    }

    if (lease.status !== 'active' || lease.expiresAt <= Date.now()) {
      if (lease.status === 'active') await expireActiveLease(lock, persona, lease, items);
      throw new PersonaLeaseLostError(
        persona.id,
        `Persona lease ${JSON.stringify(lease.id)} expired before completion.`,
      );
    }
    if (activity.status !== 'running' || activity.leaseId !== lease.id) {
      throw new PersonaLeaseLostError(
        persona.id,
        `Persona Activity ${JSON.stringify(activity.id)} is not running under lease `
        + `${JSON.stringify(lease.id)}.`,
      );
    }

    const now = Math.max(Date.now(), activity.updatedAt, lease.renewedAt);
    const status = input.status ?? 'completed';
    const completed = await saveActivity(lock, {
      ...activity,
      status,
      ...(input.outcomeRef !== undefined ? { outcomeRef: input.outcomeRef } : {}),
      ...(input.error !== undefined ? { error: input.error } : { error: undefined }),
      updatedAt: now,
      completedAt: now,
    });
    const completedItem = await terminalMailboxProjection(lock, item, completed, now);
    await projectPersonaLifecycle(lock, persona.id, 'idle', now);
    const released = await saveLeaseHead(lock, {
      ...lease,
      status: 'released',
      releasedAt: now,
    });
    return { activity: completed, mailboxItem: completedItem, lease: released };
  });
}

/** Coherent inspection snapshot across the runtime's multi-file projection. */
export async function listPersonaRuntimeBundle(
  personaId: string,
): Promise<import('./store').PersonaBundle | null> {
  assertSafeCollectionId(personaId);
  return withPersonaRuntimeLock(personaId, async (lock) => {
    const persona = await getPersona(personaId);
    if (!persona) return null;
    const items = await listPersonaMailboxItems(personaId);
    const head = await reconcilePersonaLeaseHead(lock, personaId);
    if (head?.status === 'active') {
      const activity = await getPersonaActivity(head.activityId);
      if (!activity || activity.personaId !== persona.id) {
        await expireActiveLease(lock, persona, head, items);
      } else if (isTerminalActivity(activity)) {
        await reconcileTerminalLease(lock, persona, head, activity, items);
      } else if (activity.status === 'waiting') {
        await reconcileWaitingLease(lock, persona, head, activity, items);
      } else {
        const item = findMailboxForActivity(persona.id, items, activity.id);
        if (!item) {
          await expireActiveLease(lock, persona, head, items);
        } else if (item.status === 'queued' || head.expiresAt <= Date.now()) {
          await expireActiveLease(lock, persona, head, items);
        } else {
          // A live claimed acquisition is authoritative. Repair lagging
          // Activity/mailbox/lifecycle projections without exposing its opaque
          // fence through this read API.
          await repairActiveClaim(lock, persona, head, item, activity);
        }
      }
    } else if (head?.status === 'released') {
      const activity = await getPersonaActivity(head.activityId);
      if (activity && activity.personaId === persona.id && isTerminalActivity(activity)) {
        await reconcileTerminalLease(lock, persona, head, activity, items);
      }
    }
    return listPersonaBundle(personaId);
  });
}
