<#
.SYNOPSIS
    Side-effect-free decision helpers shared by the Windows installer and uninstaller.

.DESCRIPTION
    This file is safe to dot-source from Pester. Functions here calculate plans,
    launcher content, and manifest payloads. They do not prompt, install packages,
    change policy or PATH, write files, invoke Git/npm, or delete directories.
#>

function Test-CommandAvailable {
    param(
        [Parameter(Mandatory)] [string]$CommandName,
        [scriptblock]$CommandResolver = { param($Name) Get-Command $Name -ErrorAction SilentlyContinue }
    )

    return [bool](& $CommandResolver $CommandName)
}

function Test-WingetAvailable {
    param(
        [scriptblock]$CommandResolver = { param($Name) Get-Command $Name -ErrorAction SilentlyContinue }
    )

    return Test-CommandAvailable -CommandName 'winget' -CommandResolver $CommandResolver
}

function Get-DefaultInstallDirectory {
    param(
        [AllowEmptyString()] [string]$LocalAppData,
        [Parameter(Mandatory)] [string]$HomeDirectory
    )

    $root = if ([string]::IsNullOrWhiteSpace($LocalAppData)) { $HomeDirectory } else { $LocalAppData }
    return Join-Path $root 'FLUJO'
}

function Resolve-InstallDirectory {
    param(
        [AllowEmptyString()] [string]$RequestedPath,
        [Parameter(Mandatory)] [string]$DefaultPath
    )

    $selected = if ([string]::IsNullOrWhiteSpace($RequestedPath)) { $DefaultPath } else { $RequestedPath.Trim() }
    return [Environment]::ExpandEnvironmentVariables($selected)
}

function Get-InstallIntent {
    param(
        [Parameter(Mandatory)] [string]$InstallDirectory,
        [Parameter(Mandatory)] [bool]$PathExists,
        [Parameter(Mandatory)] [bool]$GitDirectoryExists,
        [bool]$DirectoryIsEmpty = $false
    )

    if ($GitDirectoryExists) {
        return [PSCustomObject]@{
            InstallDirectory = $InstallDirectory
            Action           = 'Update'
            CanProceed       = $true
            Reason           = 'Existing FLUJO Git checkout'
        }
    }

    if ($PathExists -and -not $DirectoryIsEmpty) {
        return [PSCustomObject]@{
            InstallDirectory = $InstallDirectory
            Action           = 'Reject'
            CanProceed       = $false
            Reason           = 'Target exists, is not empty, and is not a Git checkout'
        }
    }

    return [PSCustomObject]@{
        InstallDirectory = $InstallDirectory
        Action           = 'Install'
        CanProceed       = $true
        Reason           = if ($PathExists) { 'Existing empty install target' } else { 'New install target' }
    }
}

function New-PrerequisiteRecord {
    param(
        [Parameter(Mandatory)] [string]$CommandName,
        [Parameter(Mandatory)] [string]$WingetId,
        [Parameter(Mandatory)] [string]$DisplayName,
        [Parameter(Mandatory)] [bool]$Preexisting
    )

    return [PSCustomObject]@{
        Command     = $CommandName
        WingetId    = $WingetId
        DisplayName = $DisplayName
        Preexisting = $Preexisting
    }
}

function Get-PrerequisitePlan {
    param(
        [Parameter(Mandatory)] [object[]]$Prerequisites,
        [scriptblock]$CommandResolver = { param($Name) Get-Command $Name -ErrorAction SilentlyContinue }
    )

    $wingetAvailable = Test-WingetAvailable -CommandResolver $CommandResolver
    $items = foreach ($prerequisite in $Prerequisites) {
        $preexisting = Test-CommandAvailable -CommandName $prerequisite.Command -CommandResolver $CommandResolver
        $action = if ($preexisting) { 'Keep' } elseif ($wingetAvailable) { 'Install' } else { 'Blocked' }
        [PSCustomObject]@{
            Command     = [string]$prerequisite.Command
            WingetId    = [string]$prerequisite.WingetId
            DisplayName = [string]$prerequisite.DisplayName
            Preexisting = $preexisting
            Action      = $action
        }
    }

    return [PSCustomObject]@{
        WingetAvailable = $wingetAvailable
        CanInstall      = $wingetAvailable -or -not ($items | Where-Object { -not $_.Preexisting })
        Prerequisites   = @($items)
    }
}

function Get-LauncherContent {
    param([Parameter(Mandatory)] [string]$AppDir)

    return @"
@echo off
REM FLUJO launcher - generated by install.ps1
set "FLUJO_HOME=$AppDir"
if not exist "%FLUJO_HOME%\package.json" (
  echo FLUJO was not found at "%FLUJO_HOME%". Please re-run the installer.
  exit /b 1
)
cd /d "%FLUJO_HOME%"
echo Starting FLUJO ... opening http://localhost:4200
start "" http://localhost:4200
npm start %*
"@
}

function ConvertTo-InstallManifest {
    param(
        [Parameter(Mandatory)] [string]$AppDir,
        [Parameter(Mandatory)] [string]$BinDir,
        [Parameter(Mandatory)] [string]$Branch,
        [Parameter(Mandatory)] [string]$RepoUrl,
        [object[]]$Prerequisites = @(),
        [Parameter(Mandatory)] [bool]$DesktopShortcut,
        [Parameter(Mandatory)] [bool]$ExecutionPolicyChanged,
        [AllowNull()] [object]$ClaudeCli
    )

    return [PSCustomObject]@{
        schema                 = 1
        installDir             = $AppDir
        binDir                 = $BinDir
        branch                 = $Branch
        repoUrl                = $RepoUrl
        desktopShortcut        = $DesktopShortcut
        executionPolicyChanged = $ExecutionPolicyChanged
        claudeCli              = if ($ClaudeCli) {
            [PSCustomObject]@{
                installed   = [bool]$ClaudeCli.Installed
                preexisting = [bool]$ClaudeCli.Preexisting
                npmPackage  = [string]$ClaudeCli.NpmPackage
            }
        } else { $null }
        prerequisites          = @($Prerequisites | Where-Object { $_ } | ForEach-Object {
            [PSCustomObject]@{
                command     = [string]$_.Command
                wingetId    = [string]$_.WingetId
                displayName = [string]$_.DisplayName
                preexisting = [bool]$_.Preexisting
            }
        })
    }
}

function Get-KnownInstallerPrerequisites {
    return @(
        [PSCustomObject]@{ command = 'git';    wingetId = 'Git.Git';            displayName = 'Git' }
        [PSCustomObject]@{ command = 'node';   wingetId = 'OpenJS.NodeJS';      displayName = 'Node.js (includes npm)' }
        [PSCustomObject]@{ command = 'python'; wingetId = 'Python.Python.3.12'; displayName = 'Python 3.12' }
        [PSCustomObject]@{ command = 'uv';     wingetId = 'astral-sh.uv';       displayName = 'uv' }
        [PSCustomObject]@{ command = 'rg';     wingetId = 'BurntSushi.ripgrep.MSVC'; displayName = 'ripgrep' }
        [PSCustomObject]@{ command = 'ollama'; wingetId = 'Ollama.Ollama';      displayName = 'Ollama' }
    )
}

function Get-UninstallPrerequisiteDecisions {
    param(
        [AllowNull()] [object]$Manifest,
        [object[]]$KnownPrerequisites = (Get-KnownInstallerPrerequisites),
        [scriptblock]$CommandResolver = { param($Name) Get-Command $Name -ErrorAction SilentlyContinue },
        [scriptblock]$AnswerResolver = { param($Candidate) $Candidate.DefaultRemove }
    )

    $hasManifestRecords = $null -ne $Manifest -and `
        (@($Manifest.PSObject.Properties.Name) -contains 'prerequisites')
    $prerequisites = if ($hasManifestRecords) { @($Manifest.prerequisites) } else { @($KnownPrerequisites) }

    $decisions = foreach ($prerequisite in $prerequisites) {
        $present = Test-CommandAvailable -CommandName ([string]$prerequisite.command) -CommandResolver $CommandResolver
        $preexisting = if ($hasManifestRecords) { [bool]$prerequisite.preexisting } else { $true }
        $defaultRemove = $present -and -not $preexisting
        $candidate = [PSCustomObject]@{
            Command       = [string]$prerequisite.command
            WingetId      = [string]$prerequisite.wingetId
            DisplayName   = [string]$prerequisite.displayName
            Present       = $present
            Preexisting   = $preexisting
            DefaultRemove = $defaultRemove
            HasManifest   = $hasManifestRecords
        }
        $remove = if ($present) { [bool](& $AnswerResolver $candidate) } else { $false }
        [PSCustomObject]@{
            Command       = $candidate.Command
            WingetId      = $candidate.WingetId
            DisplayName   = $candidate.DisplayName
            Present       = $present
            Preexisting   = $preexisting
            DefaultRemove = $defaultRemove
            HasManifest   = $hasManifestRecords
            Remove        = $remove
        }
    }

    return @($decisions)
}
