/**
 * Pure token-usage mapping for the Claude Subscription adapter (issue #87).
 *
 * The Claude Agent SDK reports Anthropic-style usage, which splits input into
 * three buckets:
 *   - input_tokens                 — fresh input the model processed anew
 *   - cache_creation_input_tokens  — fresh input written to the prompt cache
 *   - cache_read_input_tokens      — prefix RE-READ cheaply from the cache
 *
 * The reporting defect in #87: the adapter folded ALL THREE into the headline
 * `prompt_tokens`. Because each node call spawns a fresh `query()` (no session
 * reuse) that re-sends the whole conversation, the cheap `cache_read` tokens are
 * counted again on every turn — so the displayed total grows roughly
 * quadratically and shows ~millions for a short chat, even though the
 * billable / rate-limit-relevant work is far smaller.
 *
 * This helper keeps `promptTokens` as the FULL input context of the call (so the
 * context meter stays accurate) but ALSO surfaces the re-read `cacheReadTokens`
 * separately, so the UI can present an honest "fresh (+cached)" split instead of
 * one alarming number. `cache_creation` stays inside the fresh figure — those
 * tokens really were processed fresh this turn.
 */

/** Anthropic-style usage as reported on the SDK's assistant / result messages. */
export interface SdkUsage {
  input_tokens?: number;
  output_tokens?: number;
  cache_creation_input_tokens?: number;
  cache_read_input_tokens?: number;
}

/** FLUJO-shaped usage numbers derived from an SDK run. */
export interface MappedUsage {
  /** Full input context of the call: input + cache_creation + cache_read. */
  promptTokens: number;
  /** Output tokens generated by the call. */
  completionTokens: number;
  /** Subset of `promptTokens` that was cheaply re-read from the prompt cache. */
  cacheReadTokens: number;
}

/**
 * Map an SDK run's usage into FLUJO's numbers.
 *
 * Prefers the terminal `result` message's totals. On a handoff-aborted run that
 * message never arrives, so it falls back to the last assistant turn's context
 * size (`lastTurnUsage`) plus the summed output of all turns
 * (`totalOutputTokens`) — otherwise a run that ends by routing to another node
 * would report 0 tokens.
 */
export function mapSdkUsage(
  resultUsage: SdkUsage | undefined,
  fallback?: { lastTurnUsage?: SdkUsage; totalOutputTokens?: number },
): MappedUsage {
  const contextUsage = resultUsage ?? fallback?.lastTurnUsage;
  const input = contextUsage?.input_tokens ?? 0;
  const cacheCreation = contextUsage?.cache_creation_input_tokens ?? 0;
  const cacheRead = contextUsage?.cache_read_input_tokens ?? 0;

  const promptTokens = input + cacheCreation + cacheRead;
  const completionTokens = resultUsage
    ? resultUsage.output_tokens ?? 0
    : fallback?.totalOutputTokens ?? 0;

  return { promptTokens, completionTokens, cacheReadTokens: cacheRead };
}
