/** Normalize either one Anthropic request or an explicitly accumulated SDK run.
 * Input, cache writes, and cache reads are disjoint native buckets.
 * These are usage counts, not necessarily a context snapshot.
 */

/** Anthropic-style usage as reported on the SDK's assistant / result messages. */
export interface SdkUsage {
  input_tokens?: number;
  output_tokens?: number;
  cache_creation_input_tokens?: number;
  cache_read_input_tokens?: number;
}

/** FLUJO-shaped usage numbers derived from an SDK run. */
export interface MappedUsage {
  /** Full processed input: input + cache_creation + cache_read. */
  promptTokens: number;
  /** Output tokens generated by the call. */
  completionTokens: number;
  /** Subset of `promptTokens` that was cheaply re-read from the prompt cache. */
  cacheReadTokens: number;
  /** Subset of `promptTokens` written to Anthropic's prompt cache. */
  cacheWriteTokens: number;
  /** Full input plus output, matching the OpenAI-shaped adapter contract. */
  totalTokens: number;
}

/** Normalize token buckets after the caller has selected the correct scope. */
export function mapSdkUsage(usage: SdkUsage | undefined): MappedUsage {
  const input = usage?.input_tokens ?? 0;
  const cacheCreation = usage?.cache_creation_input_tokens ?? 0;
  const cacheRead = usage?.cache_read_input_tokens ?? 0;
  const promptTokens = input + cacheCreation + cacheRead;
  const completionTokens = usage?.output_tokens ?? 0;

  return {
    promptTokens,
    completionTokens,
    totalTokens: promptTokens + completionTokens,
    cacheReadTokens: cacheRead,
    cacheWriteTokens: cacheCreation,
  };
}
