/**
 * Pure token-usage mapping for the OpenAI-compatible completion path (issue #89,
 * sibling of #87).
 *
 * OpenAI-shaped completions report a flat `prompt_tokens` that already INCLUDES
 * any prefix re-read cheaply from the provider's automatic prompt cache. That
 * cached subset is broken out under `prompt_tokens_details.cached_tokens`.
 *
 * The #89 concern: a ProcessNode bound to several MCP servers serializes a large
 * (~20k-token) tool-definition prefix into every stateless Chat Completions
 * call, and the full history is re-sent each turn. Providers auto-cache that
 * prefix and bill the re-read at a discount, but the headline `prompt_tokens`
 * still counts it — so the displayed total looks far larger than the real cost.
 *
 * This helper keeps `promptTokens` as the FULL input context of the call (so the
 * context meter stays accurate) but ALSO surfaces the re-read `cacheReadTokens`
 * separately, so the UI can present an honest "fresh (+cached)" split instead of
 * one alarming number — identical semantics to the Claude path's mapSdkUsage.
 *
 * The OpenAI adapter returns the provider completion unchanged, so this mapping
 * applies to every OpenAI-compatible provider that populates
 * `prompt_tokens_details.cached_tokens`.
 */

/** OpenAI-shaped usage, as reported on a ChatCompletion's `usage` field. */
export interface OpenAiUsageLike {
  prompt_tokens?: number;
  completion_tokens?: number;
  total_tokens?: number;
  prompt_tokens_details?: { cached_tokens?: number } | null;
}

/** FLUJO-shaped usage numbers derived from an OpenAI-compatible completion. */
export interface MappedOpenAiUsage {
  /** Full input context of the call (already inclusive of any cached re-read). */
  promptTokens: number;
  /** Output tokens generated by the call. */
  completionTokens: number;
  /** prompt + completion, as the provider reported it. */
  totalTokens: number;
  /**
   * Subset of `promptTokens` cheaply re-read from the provider's prompt cache.
   * Omitted entirely when the provider does not report it, so consumers can
   * tell "0 cached" apart from "provider doesn't report caching".
   */
  cacheReadTokens?: number;
}

/**
 * Map an OpenAI-compatible completion's `usage` into FLUJO's numbers.
 *
 * Returns `undefined` when the completion carried no usage block (so callers can
 * attach usage only when the provider actually reported it).
 */
export function mapOpenAiUsage(
  rawUsage: OpenAiUsageLike | undefined | null,
): MappedOpenAiUsage | undefined {
  if (!rawUsage) return undefined;

  const cachedTokens = rawUsage.prompt_tokens_details?.cached_tokens;
  return {
    promptTokens: rawUsage.prompt_tokens ?? 0,
    completionTokens: rawUsage.completion_tokens ?? 0,
    totalTokens: rawUsage.total_tokens ?? 0,
    ...(cachedTokens != null ? { cacheReadTokens: cachedTokens } : {}),
  };
}
